<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-17 04:21
=======
# Generated by Django 5.2.3 on 2025-07-01 07:10
>>>>>>> new

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('food_pic', models.ImageField(upload_to='images/')),
                ('food_name', models.CharField(max_length=200)),
=======
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> new
            ],
        ),
    ]
